server:
  port: 8080

spring:
  application:
    name: sanJy

  ai:
    openai:
      api-key: ${SANJY_OPENAI_API_KEY}
      organization-id: ${SANJY_OPENAI_ORGANIZATION_ID}
      project-id: ${SANJY_OPENAI_PROJECT_ID}
    vectorstore:
      pgvector:
        dimensions: 1536
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/diet_control
    username: admin_usr
    password: admin_pass

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
#              advisor: DEBUG
