server:
  port: 8080

spring:
  application:
    name: sanJy

  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This server provides weather information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
    openai:
      api-key: ${SANJY_OPENAI_API_KEY}
      organization-id: ${SANJY_OPENAI_ORGANIZATION_ID}
      project-id: ${SANJY_OPENAI_PROJECT_ID}
    vectorstore:
      pgvector:
        dimensions: 1536
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  datasource:
    url: jdbc:postgresql://localhost:5432/diet_control
    username: admin_usr
    password: admin_pass

springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-ui/**,/**/swagger-resources/**
  swagger-ui:
    path: /

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
#              advisor: DEBUG
